name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    env:
      MINT_PATH: ${{ github.workspace }}/mint/lib

    steps:
    - uses: actions/checkout@v2
    - name: brew install mint
      run: brew install mint
    - name: Cache Mint packages
      uses: actions/cache@v2
      with:
        path: ${{ env.MINT_PATH }}
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - name: mint bootstrap
      run: mint bootstrap
    - name: xcodebuild
      run: xcodebuild -sdk iphonesimulator -configuration Debug build
